<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Klassd.Auth.Core\Klassd.Auth.Core.csproj" />
    <ProjectReference Include="..\..\src\Klassd.Auth.Passwordless\Klassd.Auth.Passwordless.csproj" />
    <ProjectReference Include="..\..\src\Klassd.Auth.Passkeys\Klassd.Auth.Passkeys.csproj" />
    <ProjectReference Include="..\..\src\Klassd.Auth.OAuth\Klassd.Auth.OAuth.csproj" />
    <ProjectReference Include="..\..\src\Klassd.Auth.Webhooks\Klassd.Auth.Webhooks.csproj" />
  </ItemGroup>

</Project>
